global using Company.Template.Api.FeatureCatalog;
global using Company.Template.Application.FeatureCatalog;
global using Company.Template.Application.Products;
global using Company.Template.Infrastructure.FeatureCatalog;
global using Company.Template.Composition.Abstractions.Contexts;
global using Company.Template.Composition.Abstractions.Contracts;
global using Company.Template.Composition.AspNetCore.Contexts;
global using Company.Template.Composition.AspNetCore.Contracts;
global using Company.Template.CompositionRoot.Features;
