<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Company.Template.Application\Company.Template.Application.csproj"/>
        <ProjectReference Include="..\composition\Company.Template.Composition.AspNetCore\Company.Template.Composition.AspNetCore.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <!--#if (auth == "Keycloak") -->
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <!--#endif -->
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    </ItemGroup>

</Project>
