<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Company.Template.Application\Company.Template.Application.csproj"/>
        <ProjectReference Include="..\Company.Template.Composition.Abstractions\Company.Template.Composition.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    </ItemGroup>

</Project>
