global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Company.Template.Application.Tests.TestSupport;
global using Microsoft.EntityFrameworkCore;
global using Shouldly;
global using Xunit;
