<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Company.Template.Application\Company.Template.Application.csproj"/>
        <ProjectReference Include="..\Company.Template.Domain\Company.Template.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(EffectiveDbProvider)' != 'PostgreSql'">
        <Compile Remove="Persistence\Providers\DatabaseProviderConfigurator.PostgreSql.cs"/>
    </ItemGroup>

    <ItemGroup Condition="'$(EffectiveDbProvider)' != 'SqlServer'">
        <Compile Remove="Persistence\Providers\DatabaseProviderConfigurator.SqlServer.cs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"/>

        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Condition="'$(EffectiveDbProvider)' == 'PostgreSql'"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Condition="'$(EffectiveDbProvider)' == 'SqlServer'"/>

        <PackageReference Include="System.Security.Cryptography.Xml" PrivateAssets="all"/>
    </ItemGroup>

</Project>