<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Company.Template.Application\Company.Template.Application.csproj"/>
        <ProjectReference Include="..\Company.Template.Domain\Company.Template.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Persistence\Providers\DatabaseProviderConfigurator.PostgreSql.cs" Condition="'$(EffectiveDbProvider)' != 'PostgreSql'"/>
        <Compile Remove="Persistence\Providers\DatabaseProviderConfigurator.SqlServer.cs" Condition="'$(EffectiveDbProvider)' != 'SqlServer'"/>
        <Compile Remove="Persistence\Providers\DatabaseProviderConfigurator.MySql.cs" Condition="'$(EffectiveDbProvider)' != 'MySql'"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Persistence\Providers\PostgreSqlDatabaseProvider.cs" Condition="'$(EffectiveDbProvider)' != 'PostgreSql'"/>
        <Compile Remove="Persistence\Providers\SqlServerDatabaseProvider.cs" Condition="'$(EffectiveDbProvider)' != 'SqlServer'"/>
        <Compile Remove="Persistence\Providers\MySqlDatabaseProvider.cs" Condition="'$(EffectiveDbProvider)' != 'MySql'"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>

        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"/>

        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Condition="'$(EffectiveDbProvider)' == 'PostgreSql'"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Condition="'$(EffectiveDbProvider)' == 'SqlServer'"/>
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Condition="'$(EffectiveDbProvider)' == 'MySql'"/>

        <PackageReference Include="System.Security.Cryptography.Xml" PrivateAssets="all"/>
    </ItemGroup>

</Project>
